# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_backend:
    name: build_backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend
        shell: bash

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - uses: dorny/paths-filter@v2
      id: filter
      with: 
        filters: |
          backend:
            - 'backend/**'
    - name: install deps
      if: steps.filter.outputs.backend == 'true'
      run: yarn install --frozen-lockfile
    - name: load env variables
      if: steps.filter.outputs.backend == 'true'
      env: 
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          APP_KEYS: ${{ secrets.APP_KEYS }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
    - name: Build Strapi app
      run: |
          NODE_ENV=production yarn build
    - name: turn on app
      if: steps.filter.outputs.backend == 'true'
      run: pm2 startOrReload ecosystem.config.js
    
  build_forum:
    name: build_frontend
    needs: build_backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./forum

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - uses: dorny/paths-filter@v2
      id: filter
      with: 
        filters: |
          forum:
            - 'forum/**'
    - name: install deps --frozen-lockfile
      if: steps.filter.outputs.forum == 'true'
      run: yarn install --frozen-lockfile
    - name: load env variables
      if: steps.filter.outputs.forum == 'true'
      env: 
          NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          JWT_SECRET_GOOGLE: ${{ secrets.JWT_SECRET_GOOGLE }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
    - name: Build Forum app
      run: |
          source $GITHUB_ENV
          yarn build
    - name: start app
      if: steps.filter.outputs.forum == 'true'
      run: pm2 startOrReload ecosystem.config.js

